# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            QCB 508 | Spring 2019
tagline:          "QCB 508 | Princeton University"
description:      "<a href='https://jdstorey.github.io/asdscourse2019/'>Foundations of Applied Statistics and Data Science with Applications in Biology</a>" 
url:              https://jdstorey.github.io
baseurl:          /asdscourse2019

author:
  name:           'John Storey'

paginate:         1000
paginate_path:    "news/page:num/"

markdown:         kramdown

gems:             [jekyll-paginate]

excerpt_separator: <!--more-->

